// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4iXOEZcxb-dtX4yj2jAzQQX8eduTrSEU',
    appId: '1:581142763635:web:4e5a9c445cf06d227b3206',
    messagingSenderId: '581142763635',
    projectId: 'vtc-gestion',
    authDomain: 'vtc-gestion.firebaseapp.com',
    databaseURL: 'https://vtc-gestion-default-rtdb.firebaseio.com',
    storageBucket: 'vtc-gestion.appspot.com',
    measurementId: 'G-9VT9L4RVKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBe3v56SV3EVbukTuFgOyIX2Ue8h0RbjY',
    appId: '1:581142763635:android:a26f84e3bea7a2907b3206',
    messagingSenderId: '581142763635',
    projectId: 'vtc-gestion',
    databaseURL: 'https://vtc-gestion-default-rtdb.firebaseio.com',
    storageBucket: 'vtc-gestion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVtR4--WYFR0RjjMXhHsC6DLDMN_UEwBI',
    appId: '1:581142763635:ios:1410922adbfd62987b3206',
    messagingSenderId: '581142763635',
    projectId: 'vtc-gestion',
    databaseURL: 'https://vtc-gestion-default-rtdb.firebaseio.com',
    storageBucket: 'vtc-gestion.appspot.com',
    androidClientId: '581142763635-94mgu6p42pesngunevgefskfmo5g29ra.apps.googleusercontent.com',
    iosClientId: '581142763635-oti2caoq8o994vtk5g4grh9gjk5ekj6j.apps.googleusercontent.com',
    iosBundleId: 'com.yapi.nolimitrider',
  );
}
